services:
    app:
        image: thebiggive/php:dev-8.3
        platform: linux/amd64
        environment:
            docker: "true"
        env_file:
            - .env
        ports:
            - "30050:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - identity
            - matchbot_matchbot # used to send update messages to matchbot on dev machines
    db:
        image: mysql:8.0
        platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "30051:3306"
        environment:
            MYSQL_DATABASE: identity
            MYSQL_ROOT_PASSWORD: tbgLocal123
        networks:
            - identity
# sharing matchbot's redis as it carries symfony messages on dev machines
#    redis:
#        image: redis:7.0
#        platform: linux/amd64
#        networks:
#            - identity
networks:
    identity:
        external: false
    matchbot_matchbot:
        external: true