version: "3.7"

services:
    app:
        image: thebiggive/php:dev-8.1
        # todo review
#        working_dir: /var/www
#        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "30050:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "30051:3306"
        environment:
            MYSQL_DATABASE: identity
            MYSQL_ROOT_PASSWORD: tbgLocal123
