services:
    app:
        image: thebiggive/php:dev-8.3
        platform: linux/amd64
        environment:
            docker: "true"
        env_file:
            - .env
        ports:
            - "30050:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis

    db:
        image: mysql:8.0
        platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "30051:3306"
        environment:
            MYSQL_DATABASE: identity
            MYSQL_ROOT_PASSWORD: tbgLocal123

    redis:
        image: redis:7.0
        platform: linux/amd64
